name: helm-gpt-cmp-env

channels:
  - conda-forge
  - defaults
  - anaconda

dependencies:
  - python=3.8
  - pip

# jupyter-lab dependencies
  - ipython           
  - jupyterlab
  - matplotlib

# machine learning & data analysis dependencies
  - tqdm
  - numpy          
  - scipy
  - pandas
  - tensorboard

